### ISSUE TITLE
VITAS_model.py文件特征抽取

### ISSUE THREAD

**Issue by sol924** [CwLiuzzZ/ViTAS#1]
你好，我想直接使用ViTAS模型里面VITAS_model.py这个文件的时候，输入图像的形状是320×720，遇到了这个问题，麻烦问问要怎么解决？
![image](https://github.com/user-attachments/assets/f9d67889-a736-49e7-80f1-54827be09cda)

**Comment by CwLiuzzZ** [comment]
corss attention module 里 num_splits默认为2。多头注意力机制中，输入特征需要可以被num_splits整除，而此时你的特征的长宽中有一项为23，不能被2整除，所以报错了。你可以对图像进行进一步的padding来解决这个问题。比如我在
[ViTASIGEV](https://github.com/CwLiuzzZ/ViTAS/blob/main/toolkit/torch_lightning/pl_modules/ViTASIGEV.py)中将输入图像的长宽都padding到64的整数倍：
`padder = base_function.InputPadder(imgL.shape,64, mode = 'replicate')`
